In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
soya1= pd.read_csv("Soyabean1.csv")

In [3]:
soya2= pd.read_csv("newdfsoyabean2019.csv")

In [4]:
soya1

              State       District Arrival_date  Sold_Amount/tonns Unnamed: 4
0       Chattisgarh    Balodabazar          Jan                6.9        NaN
1       Chattisgarh           Durg          Jan              958.5        NaN
2       Chattisgarh      Kabirdham          Jan              242.4        NaN
3       Chattisgarh        Mungeli          Jan              151.9        NaN
4       Chattisgarh         Raipur          Jan              630.2        NaN
5       Chattisgarh    Rajnandgaon          Jan             2946.9        NaN
6       Chattisgarh    Balodabazar          Feb               15.5        NaN
7       Chattisgarh           Durg          Feb              599.0        NaN
8       Chattisgarh      Kabirdham          Feb              287.3        NaN
9       Chattisgarh        Mungeli          Feb               96.5        NaN
10      Chattisgarh         Raipur          Feb              312.9        NaN
11      Chattisgarh    Rajnandgaon          Feb             4166.9        NaN
12      Chattisgarh    Balodabazar          Mar                4.4        NaN
13      Chattisgarh           Durg          Mar              230.6        NaN
14      Chattisgarh      Kabirdham          Mar              434.5        NaN
15      Chattisgarh        Mungeli          Mar               55.7        NaN
16      Chattisgarh         Raipur          Mar                0.2        NaN
17      Chattisgarh    Rajnandgaon          Mar             3750.6        NaN
18      Chattisgarh    Balodabazar          Apr                3.1        NaN
19      Chattisgarh           Durg          Apr              208.8        NaN
20      Chattisgarh      Kabirdham          Apr              612.3        NaN
21      Chattisgarh        Mungeli          Apr               47.8        NaN
22      Chattisgarh         Raipur          Apr              500.0        NaN
23      Chattisgarh    Rajnandgaon          Apr             4405.8        NaN
24      Chattisgarh    Balodabazar          May                5.3        NaN
25      Chattisgarh      Kabirdham          May              279.1        NaN
26      Chattisgarh        Mungeli          May              162.6        NaN
27      Chattisgarh         Raipur          May              775.4        NaN
28      Chattisgarh    Rajnandgaon          May             4126.3        NaN
29      Chattisgarh           Durg          May              234.0        NaN
...             ...            ...          ...                ...        ...
1062      rajasthan          Baran          Oct            31403.1        NaN
1063      rajasthan  Swai Madhopur          Nov              322.9        NaN
1064      rajasthan           Kota          Nov            45273.1        NaN
1065      rajasthan       Jhalawar          Nov            53503.5        NaN
1066      rajasthan    Chittorgarh          Nov             7965.2        NaN
1067      rajasthan          Bundi          Nov             3010.6        NaN
1068      rajasthan       Bhilwara          Nov               29.8        NaN
1069      rajasthan          Baran          Nov            28284.1        NaN
1070  Uttar Pradesh         Kanpur          Jan              492.0        NaN
1071  Uttar Pradesh       Lalitpur          Jan              503.5        NaN
1072  Uttar Pradesh         Kanpur          Feb              640.0        NaN
1073  Uttar Pradesh       Lalitpur          Feb              418.0        NaN
1074  Uttar Pradesh         Kanpur          Mar              565.0        NaN
1075  Uttar Pradesh       Lalitpur          Mar              233.0        NaN
1076  Uttar Pradesh         Kanpur          Apr              595.0        NaN
1077  Uttar Pradesh       Lalitpur          Apr               98.5        NaN
1078  Uttar Pradesh         Kanpur          May              669.0        NaN
1079  Uttar Pradesh       Lalitpur          May              415.5        NaN
1080  Uttar Pradesh         Kanpur          Jun              483.0        NaN
1081  Uttar Pradesh       Lalitpur          Jun              456.9        NaN
1082  Uttar Pradesh         Kanpur          Jul              704.0        NaN
1083  Uttar Pradesh       Lalitpur          Jul              745.0        NaN
1084  Uttar Pradesh         Kanpur          Aug              880.0        NaN
1085  Uttar Pradesh       Lalitpur          Aug              225.0        NaN
1086  Uttar Pradesh         Kanpur          Sep              573.0        NaN
1087  Uttar Pradesh       Lalitpur          Sep               80.4        NaN
1088  Uttar Pradesh         Kanpur          Oct              426.0        NaN
1089  Uttar Pradesh       Lalitpur          Oct              329.5        NaN
1090  Uttar Pradesh         Kanpur          Nov              600.0        NaN
1091  Uttar Pradesh       Lalitpur          Nov             8191.0        NaN

[1092 rows x 5 columns]

In [6]:
soya2

     arrival_date           state   variety     district  modal_price
0             Jan  Madhya Pradesh     Other      Shehdol  3295.833333
1             Jan  Madhya Pradesh  Soyabeen   Ashoknagar  3357.142857
2             Jan  Madhya Pradesh     Other      Vidisha  3404.130435
3             Jan  Madhya Pradesh     Other      Umariya  3440.000000
4             Jan  Madhya Pradesh     Other    Tikamgarh  3315.000000
5             Jan  Madhya Pradesh     Other     Shivpuri  3522.909091
6             Jan  Madhya Pradesh     Other      Sheopur  3472.857143
7             Jan  Madhya Pradesh     Other     Shajapur  3572.171171
8             Jan  Madhya Pradesh     Other        Seoni  3075.000000
9             Jan  Madhya Pradesh     Other       Sehore  3501.000000
10            Jan  Madhya Pradesh     Other        Satna  3191.562500
11            Jan  Madhya Pradesh     Other        Sagar  3247.500000
12            Jan  Madhya Pradesh     Other         Rewa  3192.400000
13            Jan  Madhya Pradesh     Other       Ratlam  3575.431818
14            Jan  Madhya Pradesh     Other      Rajgarh  3563.727273
15            Jan  Madhya Pradesh     Other       Raisen  3295.680000
16            Jan  Madhya Pradesh     Other        Panna  3110.000000
17            Jan  Madhya Pradesh     Other      Neemuch  3440.260870
18            Jan  Madhya Pradesh     Other  Narsinghpur  3440.363636
19            Jan  Madhya Pradesh     Other     Mandsaur  3543.820000
20            Jan  Madhya Pradesh     Other     Khargone  3541.417910
21            Jan  Madhya Pradesh     Other      Khandwa  3548.933333
22            Jan  Madhya Pradesh     Other       Indore  3452.522727
23            Jan  Madhya Pradesh     Other  Hoshangabad  3123.100000
24            Jan  Madhya Pradesh  Soyabeen      Badwani  3024.000000
25            Jan  Madhya Pradesh     Other         Guna  3471.186813
26            Jan  Madhya Pradesh  Soyabeen       Bhopal  3404.000000
27            Jan  Madhya Pradesh  Soyabeen   Chhindwara  2769.000000
28            Jan  Madhya Pradesh    Yellow        Damoh  3448.806452
29            Jan  Madhya Pradesh    Yellow   Chhindwara  3327.222222
...           ...             ...       ...          ...          ...
1972          Dec  Madhya Pradesh    Yellow        Harda  3546.333333
1973          Dec  Madhya Pradesh    Yellow        Dewas  3516.909091
1974          Dec  Madhya Pradesh    Yellow        Datia  3000.000000
1975          Dec  Madhya Pradesh    Yellow        Damoh  3426.111111
1976          Dec  Madhya Pradesh    Yellow   Chhindwara  3392.000000
1977          Dec  Madhya Pradesh    Yellow   Chhatarpur  3400.000000
1978          Dec  Madhya Pradesh    Yellow    Burhanpur  3441.200000
1979          Dec  Madhya Pradesh    Yellow       Bhopal  3272.000000
1980          Dec  Madhya Pradesh    Yellow         Dhar  3541.120000
1981          Dec     Maharashtra     Other      Jalgaon  3450.428571
1982          Dec  Madhya Pradesh    Yellow      Neemuch  3582.200000
1983          Dec  Madhya Pradesh    Yellow      Rajgarh  3519.843750
1984          Dec     Maharashtra     Other      Hingoli  3530.166667
1985          Dec     Maharashtra     Other   Chandrapur  3543.250000
1986          Dec     Maharashtra     Other     Buldhana  3387.500000
1987          Dec     Maharashtra     Other         Beed  3541.500000
1988          Dec     Maharashtra     Other   Aurangabad  3553.666667
1989          Dec     Maharashtra     Other    Amarawati  3440.428571
1990          Dec     Maharashtra     Other        Akola  3240.000000
1991          Dec  Madhya Pradesh    Yellow       Raisen  3247.363636
1992          Dec     Maharashtra     Other   Ahmednagar  3477.583333
1993          Dec  Madhya Pradesh    Yellow       Ujjain  3583.214286
1994          Dec  Madhya Pradesh    Yellow    Tikamgarh  3350.000000
1995          Dec  Madhya Pradesh    Yellow     Shivpuri  3503.000000
1996          Dec  Madhya Pradesh    Yellow     Shajapur  3466.772727
1997          Dec  Madhya Pradesh    Yellow       Sehore  3492.428571
1998          Dec  Madhya Pradesh    Yellow        Sagar  3470.818182
1999          Dec  Madhya Pradesh    Yellow       Ratlam  3572.454545
2000          Dec  Madhya Pradesh    Yellow      Vidisha  3465.900000
2001          Dec     Chattisgarh     Local  Rajnandgaon  3576.750000

[2002 rows x 5 columns]

In [7]:
count = soya2.groupby(['state']).count() 
print(count)

                arrival_date  variety  district  modal_price
state
Chattisgarh              106      106       106          106
Gujarat                  137      137       137          137
Karnataka                 86       86        86           86
Madhya Pradesh          1063     1063      1063         1063
Maharashtra              476      476       476          476
Manipur                    4        4         4            4
Rajasthan                106      106       106          106
Uttar Pradesh             24       24        24           24

In [9]:
count1 = soya1.groupby(['State']).count() 
print(count1)

               District  Arrival_date  Sold_Amount/tonns  Unnamed: 4
State
Chattisgarh          66            66                 66           0
Gujarat              99            99                 99           0
MP                  454           454                454           0
Manipur              55            55                 55           0
Uttar Pradesh        22            22                 22           0
karnataka            68            68                 68           0
maharastra          242           242                242           1
rajasthan            86            86                 86           0