In [1]:
def input_new(data):
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    data=pd.read_csv('data.csv')
    X=data.iloc[:,:12].values
    z=X[-1]
    y=data.iloc[:,12].values
    #Lable Encode first column
    from sklearn.preprocessing import LabelEncoder,OneHotEncoder
    labelencoder_X = LabelEncoder()
    X[:,0] = labelencoder_X.fit_transform(X[:,0])
    X[:,1] = labelencoder_X.fit_transform(X[:,1])
    X[:,4] = labelencoder_X.fit_transform(X[:,4])
    X[:,7] = labelencoder_X.fit_transform(X[:,7])
    #take onehotencoder
    onehotencoder = OneHotEncoder(categorical_features = [0,1,4,7])
    X =  onehotencoder.fit_transform(X).toarray()
    z=X[-1].reshape(1, -1)
    X=X[:-1,:]
    y=y[:-1]
    from sklearn.ensemble import RandomForestRegressor
    regressor = RandomForestRegressor(n_estimators = 2, random_state = 0)
    regressor.fit(X, y)

    # Predicting a new result
    y_pred = regressor.predict(X)
    data.loc[data.count()-1,'Expected Yield(kg/ha)']=y_pred

    return y_pred

In [2]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('soybean2010-2018_final.csv')

In [3]:
if df.columns[0] == 'Unnamed: 0':
    del df['Unnamed: 0']

In [4]:
df

,Year,District,Sowing Area(Lakh ha),Estimated Production(Lakh metric tonnes),Soil_types,Altitude(m),Humidity(%),Basins,Rainfall(mm),Max Temperature,Min Temperature,Avg Temperature,Expected Yield(kg/ha)
0,2010,Ujjain,4.435000,5.526000,Medium Black,494,70.750000,Chambal Basin,713.500000,32.500000,24.000000,27.750000,1246.000000
1,2010,Mandsaur,2.580000,2.830000,Medium Black,440,67.250000,Chambal Basin,676.800000,33.750000,25.000000,28.750000,1097.000000
2,2010,Neemuch,1.250000,1.489000,Medium Black,452,65.250000,Chambal Basin,821.700000,33.750000,25.000000,29.000000,1191.000000
3,2010,Ratlam,2.046000,2.508000,Medium Black,480,70.500000,Chambal Basin,689.000000,33.250000,24.250000,28.000000,1226.000000
4,2010,Dewas,3.181000,3.722000,Medium Black,535,72.500000,Narmada Basin,785.100000,32.250000,24.000000,27.750000,1170.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,2018,Sidhi,0.044250,0.032250,Red and Yellow,272,70.875000,Son Basin,1191.612500,31.875000,23.906250,27.500000,719.500000
456,2018,Datia,0.072250,0.043500,Mixed Red and Black,420,56.406250,Sindh Basin,778.587500,35.750000,27.968750,31.812500,740.500000
457,2018,Bhind,0.003333,0.002333,Alluvium,192,53.750000,Sindh Basin,601.214286,36.964286,29.035714,32.892857,730.500000
458,2018,Morena,0.011143,0.007429,Alluvium,177,53.607143,Sindh Basin,638.671429,36.785714,28.785714,32.642857,753.285714
459,2019,Ratlam,2.351000,1.697000,Medium Black,480,74.360000,Chambal Basin,75.630000,31.250000,24.850000,27.850000,744.500000

In [5]:
'''df['Sowing Area(Lakh ha)'] = df.groupby(['District'])['Sowing Area(Lakh ha)'].transform(lambda x: x.fillna(x.mean()))
df['Estimated Production(Lakh metric tonnes)'] = df.groupby(['District'])['Estimated Production(Lakh metric tonnes)'].transform(lambda x: x.fillna(x.mean()))
df['Humidity(%)'] = df.groupby(['District'])['Humidity(%)'].transform(lambda x: x.fillna(x.mean()))
df['Rainfall(mm)'] = df.groupby(['District'])['Rainfall(mm)'].transform(lambda x: x.fillna(x.mean()))
df['Max Temperature'] = df.groupby(['District'])['Max Temperature'].transform(lambda x: x.fillna(x.mean()))
df['Min Temperature'] = df.groupby(['District'])['Min Temperature'].transform(lambda x: x.fillna(x.mean()))
df['Avg Temperature'] = df.groupby(['District'])['Avg Temperature'].transform(lambda x: x.fillna(x.mean()))
df['Expected Yield(kg/ha)'] = df.groupby(['District'])['Expected Yield(kg/ha)'].transform(lambda x: x.fillna(x.mean()))
'''

"df['Sowing Area(Lakh ha)'] = df.groupby(['District'])['Sowing Area(Lakh ha)'].transform(lambda x: x.fillna(x.mean()))\ndf['Estimated Production(Lakh metric tonnes)'] = df.groupby(['District'])['Estimated Production(Lakh metric tonnes)'].transform(lambda x: x.fillna(x.mean()))\ndf['Humidity(%)'] = df.groupby(['District'])['Humidity(%)'].transform(lambda x: x.fillna(x.mean()))\ndf['Rainfall(mm)'] = df.groupby(['District'])['Rainfall(mm)'].transform(lambda x: x.fillna(x.mean()))\ndf['Max Temperature'] = df.groupby(['District'])['Max Temperature'].transform(lambda x: x.fillna(x.mean()))\ndf['Min Temperature'] = df.groupby(['District'])['Min Temperature'].transform(lambda x: x.fillna(x.mean()))\ndf['Avg Temperature'] = df.groupby(['District'])['Avg Temperature'].transform(lambda x: x.fillna(x.mean()))\ndf['Expected Yield(kg/ha)'] = df.groupby(['District'])['Expected Yield(kg/ha)'].transform(lambda x: x.fillna(x.mean()))\n"

In [6]:
df

,Year,District,Sowing Area(Lakh ha),Estimated Production(Lakh metric tonnes),Soil_types,Altitude(m),Humidity(%),Basins,Rainfall(mm),Max Temperature,Min Temperature,Avg Temperature,Expected Yield(kg/ha)
0,2010,Ujjain,4.435000,5.526000,Medium Black,494,70.750000,Chambal Basin,713.500000,32.500000,24.000000,27.750000,1246.000000
1,2010,Mandsaur,2.580000,2.830000,Medium Black,440,67.250000,Chambal Basin,676.800000,33.750000,25.000000,28.750000,1097.000000
2,2010,Neemuch,1.250000,1.489000,Medium Black,452,65.250000,Chambal Basin,821.700000,33.750000,25.000000,29.000000,1191.000000
3,2010,Ratlam,2.046000,2.508000,Medium Black,480,70.500000,Chambal Basin,689.000000,33.250000,24.250000,28.000000,1226.000000
4,2010,Dewas,3.181000,3.722000,Medium Black,535,72.500000,Narmada Basin,785.100000,32.250000,24.000000,27.750000,1170.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,2018,Sidhi,0.044250,0.032250,Red and Yellow,272,70.875000,Son Basin,1191.612500,31.875000,23.906250,27.500000,719.500000
456,2018,Datia,0.072250,0.043500,Mixed Red and Black,420,56.406250,Sindh Basin,778.587500,35.750000,27.968750,31.812500,740.500000
457,2018,Bhind,0.003333,0.002333,Alluvium,192,53.750000,Sindh Basin,601.214286,36.964286,29.035714,32.892857,730.500000
458,2018,Morena,0.011143,0.007429,Alluvium,177,53.607143,Sindh Basin,638.671429,36.785714,28.785714,32.642857,753.285714
459,2019,Ratlam,2.351000,1.697000,Medium Black,480,74.360000,Chambal Basin,75.630000,31.250000,24.850000,27.850000,744.500000

In [7]:
user_input=int(input("enter the value u want to predict"))
for i in range(1,user_input+1):
    year=int(input("enter the year"))
    dist=str(input("enter the district"))
    rain=eval(input("enter the rainfall"))
    esti_prod=eval(input("enter the estimated product"))
    showing=eval(input("enter the showing area"))
    maxtemp=eval(input("enter the max temperature"))
    mintemp=eval(input("enter the min temperature"))
    avgtemp=eval(input("enter the avg temperature"))
    humi=eval(input("enter the humi"))
    yiel=eval(input("enter the yield"))
    ind=0
    for j in range(0,52):
        if(df["District"][j]==dist):
            ind=j
            break
    soil_t =df[df['District']==dist]['Soil_types'].head(1)[ind]
    basin =df[df['District']==dist]['Basins'].head(1)[ind]
    alti =df[df['District']==dist]['Altitude(m)'].head(1)[ind]
    df1=pd.DataFrame({'Year': year,'District':dist,'Sowing Area(Lakh ha)':showing,'Rainfall(mm)':rain,'Soil_types':soil_t ,'Estimated Production(Lakh metric tonnes)':esti_prod,'Basins':basin ,'Humidity(%)':humi,'Altitude(m)': alti,'Max Temperature':maxtemp,'Min Temperature':mintemp,'Avg Temperature':avgtemp,'Expected Yield(kg/ha)':yiel},index=[len(df)])
    #df=df.append(df1)
    #df1 = pd.DataFrame([[year, dist,showing, esti_prod, soil_t, alti, humi, basin, rain, maxtemp, mintemp, avgtemp, 0]], columns=['Year','District','Sowing Area(Lakh ha)','Estimated Production(Lakh metric tonnes)','Soil_types','Altitude(m)','Humidity(%)','Basins','Rainfall(mm)','Max Temperature','Min Temperature','Avg Temperature', 'Expected Yield(kg/ha)'])
    df=df.append(df1)

'user_input=int(input("enter the value u want to predict"))\nfor i in range(1,user_input+1):\n    year=int(input("enter the year"))\n    dist=str(input("enter the district"))\n    rain=eval(input("enter the rainfall"))\n    esti_prod=eval(input("enter the estimated product"))\n    showing=eval(input("enter the showing area"))\n    maxtemp=eval(input("enter the max temperature"))\n    mintemp=eval(input("enter the min temperature"))\n    avgtemp=eval(input("enter the avg temperature"))\n    humi=eval(input("enter the humi"))\n    yiel=eval(input("enter the yield"))\n    ind=0\n    for j in range(0,52):\n        if(df["District"][j]==dist):\n            ind=j\n            break\n    soil_t =df[df[\'District\']==dist][\'Soil_types\'].head(1)[ind]\n    basin =df[df[\'District\']==dist][\'Basins\'].head(1)[ind]\n    alti =df[df[\'District\']==dist][\'Altitude(m)\'].head(1)[ind]\n    df1=pd.DataFrame({\'Year\': year,\'District\':dist,\'Sowing Area(Lakh ha)\':showing,\'Rainfall(mm)\':rain,\'Soil_types\':soil_t ,\'Estimated Production(Lakh metric tonnes)\':esti_prod,\'Basins\':basin ,\'Humidity(%)\':humi,\'Altitude(m)\': alti,\'Max Temperature\':maxtemp,\'Min Temperature\':mintemp,\'Avg Temperature\':avgtemp,\'Expected Yield(kg/ha)\':yiel},index=[len(df)])\n    #df=df.append(df1)\n    #df1 = pd.DataFrame([[year, dist,showing, esti_prod, soil_t, alti, humi, basin, rain, maxtemp, mintemp, avgtemp, 0]], columns=[\'Year\',\'District\',\'Sowing Area(Lakh ha)\',\'Estimated Production(Lakh metric tonnes)\',\'Soil_types\',\'Altitude(m)\',\'Humidity(%)\',\'Basins\',\'Rainfall(mm)\',\'Max Temperature\',\'Min Temperature\',\'Avg Temperature\', \'Expected Yield(kg/ha)\'])\n    df=df.append(df1)'

In [8]:
df = df[['Year','District','Sowing Area(Lakh ha)','Estimated Production(Lakh metric tonnes)','Soil_types','Altitude(m)','Humidity(%)','Basins','Rainfall(mm)','Max Temperature','Min Temperature','Avg Temperature','Expected Yield(kg/ha)']]

In [9]:
final=input_new(df)

In [ ]:
data.to_csv(r'/home/akash/soyabean/work with 2010_2018/soybean2010-2018_final.csv')

In [ ]:
import plotly.express as px
# iris = px.data.iris()
#fig = px.scatter_3d(data, x=data['Year'], y=data['District'], z=data['Expected Yield(kg/ha)'],color ='District')
fig = px.line(data, x='Year',y='Expected Yield(kg/ha)',color ='District')
fig.show()